name = "hscg-starter"
license = "MIT"
description = "Something that has evolved since 2018; originally based on a Hugo theme called “Tale” but now with little resemblance thereto."
min_version = "0.74.3"

tags = ["tags"]

[author]
  name = "Your name goes here"
  homepage = "https://www.example.com" # Your home page URL goes here

